name: 'SAMPLE-ACTION' #TODO: Set the name of the action
description: 'Gets version information from a .csproj file.'
inputs:
  repo-owner-and-name:  # id of input
    description: 'The repository owner and name separated by a forward slash.'
    required: true
  tag-name: # The name of the tag
    description: 'The name of the tag to check.'
    required: true
  repo-token:
    description: 'The token/secret for access to the repository.'
    required: true
outputs:
  tag-exists:
    description: 'True if the tag exists.'
runs:
  using: 'node12'
  main: 'dist/index.js'